const Title = {
    title: {
        ru: "Резюме Владислав Шапошник",
        en: "Rezume Vladyslav Shaposhnyk",
        ua: "Резюме Владислав Шапошник",
        cz: "Životopis Vladislav Šapošník",
    },
};
const langArr = {
    lsg_header_home: { ru: "Главная", en: "Home", ua: "Головна", cz: "Domov" },
    lsg_header_skills: {
        ru: "Навыки",
        en: "Skills",
        ua: "Вмiння",
        cz: "Dovednosti",
    },
    lsg_header_portfolio: {
        ru: "Портфолио",
        en: "Portfolio",
        ua: "Портфолiо",
        cz: "Portfolio",
    },
    lsg_header_about_me: {
        ru: "Обо мне",
        en: "About Me",
        ua: "Про мене",
        cz: "O mně",
    },
    lsg_header_work: { ru: "Работа", en: "Work", ua: "Робота", cz: "Práce" },
    lsg_header_education: {
        ru: "Образование",
        en: "Education",
        ua: "Освiта",
        cz: "Vzdělání",
    },
    lsg_header_languages: {
        ru: "Языки",
        en: "Languages",
        ua: "Мови",
        cz: "Jazyky",
    },
    lsg_header_hobbies: {
        ru: "Хобби",
        en: "Hobbies",
        ua: "Хобi",
        cz: "Záliby",
    },
    lsg_header_Characteristic: {
        ru: "Обо мне",
        en: "About Me",
        ua: "Про мене",
        cz: "O mně",
    },
    lsg_main_velcome: {
        ru: "Добро пожаловать на мою страницу.",
        en: "Welcome to my page.",
        ua: "Ласкаво просимо на мою сторiнку.",
        cz: "Vítejte na mé stránce.",
    },
    lsg_main_my_name: {
        ru: "Я Владислав Шапошник",
        en: "I'm Vladyslav Shaposhnyk",
        ua: "Мене звати Владислав Шапошник",
        cz: "Jmenuji se Vladislav Šapošnik",
    },
    lsg_main_search_work1: {
        ru: "Ищу работу в сфере IT технологий.",
        en: "I'm looking for a job in the field of IT technologies.",
        ua: "Шукаю роботу в галузi iТ-технологiй.",
        cz: "Hledám práci v oblasti IT technologií.",
    },
    lsg_main_search_work2: {
        ru: "С подробной информацией обо мне можете ознакомиться на соответствующих вкладках этой страницы.",
        en: "You can find detailed information about me on the respective tabs of this page.",
        ua: "Докладну iнформацiю про мене ви можете знайти на вiдповiдних вкладках цiєї сторiнки.",
        cz: "Podrobné informace o mně můžete najít na příslušných kartách této stránky.",
    },
    lsg_main_search_work3: {
        ru: "Если у Вас есть для меня предложения, пожалуйста свяжитесь со мной.",
        en: "If you have any offers for me, please get in touch.",
        ua: "Якщо у вас є пропозицiї для мене, будь ласка, зв'яжiться зi мною.",
        cz: "Pokud máte pro mě nabídky, prosím, kontaktujte mě.",
    },
    lsg_main_character_title: {
        ru: "Самооценка",
        en: "Self-Assessment",
        ua: "Самооцiнка",
        cz: "Sebehodnocení",
    },
    lsg_main_character_text: {
        ru: "Опытный специалист с фокусом на достижении результатов. Мои сильные стороны включают в себя стратегическое мышление, аналитические навыки и умение эффективно работать в команде. Настойчивость – это ключевая часть моего подхода к работе: я готов преодолевать трудности и находить решения, несмотря на сложности. Я постоянно стремлюсь к профессиональному развитию и открыт для новых вызовов. Стремлюсь к достижению высоких стандартов качества в своей работе, а также готов к обучению и внесению положительного вклада в успех команды.",

        en: "Experienced professional with a focus on achieving results. My strengths include strategic thinking, analytical skills, and the ability to work effectively in a team. Persistence is a key part of my approach to work: I am ready to overcome challenges and find solutions despite difficulties. I am constantly striving for professional development and open to new challenges. I aim to achieve high standards of quality in my work and am ready to learn and contribute to the team's success.",
        ua: "Досвiдчений фахiвець з фокусом на досягненнi результатiв. Мої сильнi сторони включають стратегiчне мислення, аналiтичнi навички та здатнiсть ефективно працювати в командi. Наполегливiсть - ключова частина мого пiдходу до роботи: я готовий подолати труднощi та знаходити рiшення незважаючи на складнощi. Я постiйно прагну до професiйного розвитку та вiдкритий для нових викликiв. Мета - досягти високих стандартiв якостi в своїй роботi та готовий вчитися та вносити позитивний внесок у успiх команди.",
        cz: "Zkušený odborník s důrazem na dosahování výsledků. Mezi mé silné stránky patří strategické myšlení, analytické dovednosti a schopnost efektivně pracovat v týmu. Vytrvalost je klíčovou součástí mého přístupu k práci: jsem připraven překonávat obtíže a hledat řešení navzdory složitostem. Neustále se snažím o profesionální rozvoj a jsem otevřen novým výzvám. Usiluji o dosažení vysokých standardů kvality ve své práci a jsem připraven se učit a přispívat k úspěchu týmu.",
    },
    lsg_main_languages: {
        ru: "Языковые навыки",
        en: "Language Skills",
        ua: "Мовнi навички",
        cz: " Jazykové dovednosti",
    },
    lsg_main_english: {
        ru: "Английский",
        en: "English",
        ua: "Англiйська",
        cz: "Angličtina",
    },
    lsg_main_cheh: { ru: "Чешский", en: "Czech", ua: "Чеська", cz: "Čeština" },
    lsg_main_rus: {
        ru: "Русский",
        en: "Russian",
        ua: "Росiйська",
        cz: "Ruština",
    },
    lsg_main_ukranian: {
        ru: "Украинский",
        en: "Ukrainian",
        ua: "Українська",
        cz: "Ukrajinština",
    },
    lsg_main_hobies_title: {
        ru: "Увлечения",
        en: "Hobbies",
        ua: " Хобi",
        cz: "Koníčky",
    },
    lsg_main_hobies_text: {
        ru: "В свободное время я с удовольствием занимаюсь постоянным обучением, всегда стремясь к расширению своих знаний и навыков. Люблю проводить время на пеших прогулках, используя их как возможность для анализа и размышлений. Меня привлекает красота природы, особенно леса и гор, что приносит мне не только удовольствие, но и вдохновение.",
        en: "In my free time, I enjoy continuous learning, always striving to expand my knowledge and skills. I find solace in taking long walks, using them as an opportunity for analysis and contemplation. The beauty of nature, particularly forests and mountains, captivates me, providing not only enjoyment but also inspiration.",
        ua: "У вiльний час я з задоволенням займаюсь постiйним навчанням, завжди прагнучи розширити свої знання та навички. Обожнюю проводити час на довгих прогулянках, використовуючи їх як можливiсть для аналiзу i роздумiв. Краса природи, зокрема лiсiв i гiр, захоплює мене, надаючи не лише задоволення, а й натхнення.",
        cz: "Ve svém volném čase rád pokračuji ve vzdělávání, neustále se snažíc rozšiřovat své znalosti a dovednosti. Rád trávím čas dlouhými procházkami, které využívám jako příležitost k analýze a zamyšlení. Krása přírody, zejména lesů a hor, mě pohlcuje a přináší nejen radost, ale také inspiraci.",
    },
    lsg_works_datum1: {
        ru: "март 2022 - апр. 2024",
        en: "Mar 2022 - Apr 2024",
        ua: "бер 2022 - квіт 2024",
        cz: "bře 2022 - dub 2024",
    },
    lsg_works_job_title1: {
        ru: "Складник",
        en: "Warehouse worker",
        ua: "Складник",
        cz: "Skladník",
    },
    lsg_works_jobs_firm1: {
        ru: "Чешская Республика Прага",
        en: "Chech Republic Prague",
        ua: "Чеська Республіка Прага",
        cz: "Česká Republika Praha",
    },
    lsg_works_jobs_details1: {
        ru: "Операции на складе включают в себя хранение товаров, эффективноеформирование заказов, контроль качества и подготовку товаров к отправкепотребителям для обеспечения бесперебойной и организованной цепипоставок.",
        en: "Warehouse operaons encompass the storage of goods, efficient order picking,quality control, and preparing products for shipment to consumers, ensuring aseamless and organized supply chain.",
        ua: "Операції на складі включають у себе зберігання товарів, ефективнеформування замовлень, контроль якості та підготовку товарів довідправлення споживачам для забезпечення безперебійного таорганізованого ланцюга поставок.",
        cz: "Operace ve skladu zahrnují skladování zboží, efekvní formování objednávek,kontrolu kvality a přípravu produktů k odeslání spotřebitelům za účelemzajištění plynulé a organizované dodavatelské řetězce.",
    },
    lsg_works_datum2: {
        ru: "янв. 2015 - май 2021",
        en: "Jan 2015 - May 2021",
        ua: "січ 2015 - трав 2021",
        cz: "led 2015 - kvě 2021",
    },
    lsg_works_job_title2: {
        ru: "Начальник смены",
        en: "Shift Supervisor",
        ua: "Начальник зміни",
        cz: "Vedoucí směny",
    },
    lsg_works_jobs_firm2: {
        ru: "Украина Днепропетровская область Павлоград",
        en: "Ukraine, Dnipropetrovsk Oblast, Pavlohrad",
        ua: "Україна Дніпропетровська область Павлоград",
        cz: "Ukrajina, Dnipropetrovská oblast, Pavlograd",
    },
    lsg_works_jobs_details2: {
        ru: "1. Управление всеми процессами на предприятии по добыче угля с штатом3000 сотрудников, включая управление работой. 2. Представление отчетовруководству о проведенных мероприятиях. 3. Проведение обучениясотрудников. 4. Организация процессов по предотвращению чрезвычайныхситуаций.",
        en: "1. Managing all processes at a coal mining enterprise with a staff of 3000employees, including work management. 2. Reporng to the management onconducted events. 3. Conducng employee training. 4. Organizing processes toprevent emergency situaons.",
        ua: "1. Керівництво усіма процесами на підприємстві з видобутку вугілля зштатом 3000 працівників, включаючи управління роботою.2. Звітування перед керівництвом про проведені заходи.3. Навчання працівників.4. Організація процесів щодо запобігання надзвичайних ситуацій.",
        cz: "1. Řízení všech procesů v uhelném doby se 3000 zaměstnanci, včetně řízenípráce. 2. Předkládání zpráv vedení o provedených událostech. 3. Školenízaměstnanců. 4. Organizace procesů pro prevenci mimořádných situací.",
    },
    lsg_works_datum3: {
        ru: "май 2009 - янв. 2015",
        en: "May 2009 - Jan 2015",
        ua: "трав 2009 - січ 2015",
        cz: "kvě 2009 - led 2015",
    },
    lsg_works_job_title3: {
        ru: "Мастер участка, электрик",
        en: "Area Supervisor, Electrician",
        ua: "Дільничний майстер, електрик",
        cz: "Mistr úseku, Elektrik",
    },
    lsg_works_jobs_firm3: {
        ru: "Украина Днепропетровская область Павлоград",
        en: "Ukraine, Dnipropetrovsk Oblast, Pavlohrad",
        ua: "Україна Дніпропетровська область Павлоград",
        cz: "Ukrajina, Dnipropetrovská oblast, Pavlograd",
    },
    lsg_works_jobs_details3: {
        ru: "Управление персоналом. Обслуживание электромеханическогооборудования и автоматизированных систем.",
        en: "Personnel Management. Servicing electromechanical equipment and automatedsystems.",
        ua: "Керівництво персоналом. Обслуговування електромеханічного обладнаннята автоматизованих систем.",
        cz: "Personální řízení. Obsluha elektromechanického zařízení a automazovanýchsystémů.",
    },
    lsg_educations_jobs_firm1: {
        ru: "Чешская Республика Прага",
        en: "Chech Republic Prague",
        ua: "Чеська Республіка Прага",
        cz: "Česká Republika Praha",
    },
    lsg_educations_jobs_details1: {
        ru: "Изучение HTML, CSS, Js, React, Python, SQL, Django",
        en: "Learning HTML, CSS, Js, React, Python, SQL, Django",
        ua: "Вивчення HTML, CSS, Js, React, Python, SQL, Django",
        cz: "Studium HTML, CSS, Js, React, Python, SQL, Django",
    },
    lsg_educations_name_title2: {
        ru: "Днепропетровский национальный горный университет Украины",
        en: "Dniprovskyi Naonal Mining University of Ukraine",
        ua: "Дніпропетровський національний гірничий університет України",
        cz: "Dněpropetrovská národní hornická univerzita Ukrajiny",
    },
    lsg_educations_jobs_firm2: {
        ru: "Украина Днепр",
        en: "Ukraine, Dnipro",
        ua: "Україна Дніпро",
        cz: "UkrajinaDnipro",
    },
    lsg_educations_jobs_details2: {
        ru: "Изучение технологических процессов, создание технической документации,разработка долгосрочных планов работ.",
        en: "Studying technological processes, creang technical documentaon, anddeveloping long-term work plans.",
        ua: "Вивчення технологічних процесів, створення технічної документації,розробка довгострокових планів робіт.",
        cz: "Studium technologických procesů, tvorba technické dokumentace, a vypracovánídlouhodobých plánů práce.",
    },
    lsg_footer: {
        ru: "Прага 2023",
        en: "Prague 2023",
        ua: "Прага 2023",
        cz: "Praha 2023",
    },
    SendEmailName: {
        ru: "Ваше имя",
        en: "Your name",
        ua: "Ваше ім'я",
        cz: "Vaše jméno",
    },
    SendEmailEmail: {
        ru: "Ваш емаил",
        en: "Your email",
        ua: "Ваш емейл",
        cz: "Váš e-mail",
    },
    SendEmailText: {
        ru: "Текст сообщения",
        en: "Message text",
        ua: "Текст повідомлення",
        cz: "Text zprávy",
    },
    emailButtonsSubmit: {
        ru: "Отправить",
        en: "Send",
        ua: "Надіслати",
        cz: "Odeslat",
    },
    emailButtonsSubmit: {
        ru: "Отправить",
        en: "Send",
        ua: "Надіслати",
        cz: "Odeslat",
    },
    SendEmailCancel: {
        ru: "Отмена",
        en: "Cancel",
        ua: "Скасувати",
        cz: "Zrušit",
    },
    lsg_LoadPdfWindow_question: {
        ru: "Скачать резюме в формате PDF на ",
        en: "Download resume in PDF format in ",
        ua: "Завантажити резюме у форматі PDF на ",
        cz: "Stáhnout životopis ve formátu PDF v ",
    },
    LoadPdfButtonsOK: {
        ru: "Скачать",
        en: "Download",
        ua: "Завантажити",
        cz: "Stáhnout",
    },
    LoadPdfButtonsCancel: {
        ru: "Отмена",
        en: "Cancel",
        ua: "Скасувати",
        cz: "Zrušit",
    },
    lsg_PortfolioTitlePage: {
        ru: "Моё портфолио",
        en: "My portfolio",
        ua: "Моє портфоліо",
        cz: "Můj portfólio",
    },
};
